version: '3.8'
services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - app-network
      
  postgres:
    image: postgres:15
    container_name: nestjs_postgres
    restart: always
    env_file:
      - .env.db
    ports:
      - "5472:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
   driver: bridge