export const ENV_KEYS = {
  PORT: 'PORT',

  PASSWORD_HASH: 'PASSWORD_HASH',

  JWT_ACCESS_TOKEN_EXPIRATION: 'JWT_ACCESS_TOKEN_EXPIRATION',
  JWT_REFRESH_TOKEN_EXPIRATION: 'JWT_REFRESH_TOKEN_EXPIRATION',
  JWT_SECRET: 'JWT_SECRET',

  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_DATABASE: 'DB_DATABASE',
};
